# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-15 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie_details',
            name='banner',
            field=models.CharField(default='#', max_length=1000),
        ),
    ]
