# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_game_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game_Details',
        ),
    ]
